pub mod data;
pub mod function;
pub mod keyword;
pub mod literal;
pub mod marker;
pub mod op;
pub mod operator;
pub mod program;
pub mod token;
pub mod types;
use function::Function;
use std::collections::HashMap;
use types::Type;
pub type FnTable = HashMap<String, Function>;
pub type Stack = Vec<Type>;
pub type Frame = Vec<Type>;
